version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-auth
    ports:
      - '6540:5432'
    volumes:
      - postgresAuthDB:/var/lib/postgresql/data
    env_file:
      - ./.env

volumes:
  postgresAuthDB:
